name: dreamnlaunch
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  like_button: ^2.0.4
  percent_indicator: ^4.0.1

  iconly: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.1+1

flutter_native_splash:
  image: images/dl.png
  color: "#00D5FF"









flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf
